arch: ppc64le
language: c
dist: bionic
services:
  - docker
sudo: required  
script:
  - sudo rm -rf /usr/local/share/man
  - docker run -t ppc64le/centos:7 bash -c 'ls -la /usr/local/share/; rm -rf /usr/local/share/man;touch /usr/local/share/test'
